---
title: "Cancer_Data_Extraction"
author: "Nick Ferreira"
date: '2022-05-09'
output: html_document
---
```{r}
data_files = list.files(path = "C:/Users/nkfer/OneDrive/Pace/TRI Thesis/CountyCancer_CSV",
                        pattern = "*County",
                        full.names = TRUE)

results <- c()

library(tidyr)
library(dplyr)

# Import Cancer data by County and merge into 1 

for (i in 1:length(data_files)){
  filename <- data_files[i]
  print(filename)
  data <- read.csv(filename, skip = 2)
  data$X <- NULL
  data_transform = data %>%
    separate(X95..CI, sep = "-", c("mf_95lower", "mf_95upper")) %>%
    separate(X95..CI.1, sep = "-", c("m_95lower", "m_95upper")) %>%
    separate(X95..CI.2, sep = "-", c("f_95lower", "f_95upper")) %>%
    separate(X95..CI.3, sep = "-", c("mf__95lower", "mf__95upper")) %>%
    separate(X95..CI.4, sep = "-", c("m__95lower", "m__95upper")) %>%
    separate(X95..CI.5, sep = "-", c("f__95lower", "f__95upper"))
  data_numeric = transform(data_transform, mf_95lower = as.numeric(data_transform$mf_95lower),
                           mf_95upper = as.numeric(data_transform$mf_95upper),
                           m_95lower = as.numeric(data_transform$m_95lower),
                           m_95upper = as.numeric(data_transform$m_95upper),
                           f_95lower = as.numeric(data_transform$f_95lower),
                           f_95upper = as.numeric(data_transform$f_95upper),
                           mf__95lower = as.numeric(data_transform$mf__95lower),
                           mf__95upper = as.numeric(data_transform$mf__95upper),
                           m__95lower = as.numeric(data_transform$m__95lower),
                           m__95upper = as.numeric(data_transform$m__95upper),
                           f__95lower = as.numeric(data_transform$f__95lower),
                           f__95upper = as.numeric(data_transform$f__95upper))
  county_name <- unlist(strsplit(filename, "/"))
  county_name <- unlist(strsplit(c(county_name[8]), "*County.csv"))
  data_numeric$county_name = county_name
  results <- rbind(results, data_numeric)

}
```

```{r}
# adjust column names into usable fashion

names(results) <- c("Site.of.Cancer", "Average.Annual.Cases.malefemale", "incidence.rate.per.100.000.Population.malefemale", "incidence.95lower.malefemale", "incidence.95upper.malefemale", "Average.Annual.Cases.male", "incidence.rate.per.100.000.male", "incidence.95lower.male", "incidence.95upper.male", "Average.Annual.Cases.female", "Rate.per.100.000.female", "incidence.95lower.female", "incidence.95upper.female","Average.Annual.Deaths.malefemale", "mortality.rate.per.100.000.Population.malefemale","mortality.95lower.malefemale",         "mortality.95upper.malefemale", "Average.Annual.Deaths.male", "mortality.rate.per.100.000.male","mortality.95lower.male", "mortality.95upper.male",      "Average.Annual.Deaths.female", "mortality.rate.per.100.000.female", "mortality.95lower.female", "mortality.95upper.female",                   
 "county.name")
```

```{r}
write.csv(results, file = "Cancer_Results.csv")
```

